package com.neoworksuite.neocanvas.brushes

/** Detailed organic silhouettes for foliage, grass, woody forms and ground texture. */
internal object NatureBrushes {
    private val refs = BuiltInBrushAssetRefs

    val brushes: List<BrushDefinition> = listOf(
        authoredBrush("neo.nature.leaf-broad", "Broad Leaf", "Layered broad leaves with natural directional variation.", "nature", BrushTip.Leaf, 42f, .88f, .38f, .62f, .72f,
            BrushDynamics(scatter = .32f, rotation = .2f, shapeRatio = .68f, hardness = .9f, jitter = .18f), listOf(refs.leafBroadA, refs.leafBroadB, refs.leafBroadC), refs.grainOrganic,
            StampAngleMode.DirectionJitter, angleJitter = .24f, scaleY = .72f, scatterAlong = .12f, scatterAcross = .3f, stampCount = 2, stampCountJitter = .25f, grainScale = .7f,
            pressureScatter = .35f, pressureStampCount = .45f, startTaper = .12f, endTaper = .18f),
        authoredBrush("neo.nature.leaf-fine", "Fine Leaves", "Small paired leaves for delicate shrubs and distant detail.", "nature", BrushTip.Leaf, 22f, .84f, .44f, .68f, .7f,
            BrushDynamics(scatter = .48f, rotation = .3f, shapeRatio = .55f, hardness = .92f, jitter = .22f), listOf(refs.leafFineA, refs.leafFineB), refs.grainOrganic,
            StampAngleMode.DirectionJitter, angleJitter = .34f, scaleY = .62f, scatterAlong = .16f, scatterAcross = .48f, stampCount = 3, stampCountJitter = .32f, grainScale = .55f,
            pressureScatter = .45f, pressureStampCount = .55f, startTaper = .16f, endTaper = .2f),
        authoredBrush("neo.nature.oak-cluster", "Oak Cluster", "Lobed leaf clusters for mature canopies and broken edges.", "nature", BrushTip.Leaf, 56f, .8f, .34f, .58f, .76f,
            BrushDynamics(grain = .16f, scatter = .4f, rotation = .56f, shapeRatio = .78f, hardness = .84f, jitter = .3f), listOf(refs.leafOakA, refs.leafOakB), refs.grainOrganic,
            StampAngleMode.Randomized, angleJitter = .7f, scaleY = .82f, scatterAlong = .22f, scatterAcross = .45f, stampCount = 3, stampCountJitter = .38f, grainScale = .9f,
            pressureScatter = .5f, pressureStampCount = .58f),
        authoredBrush("neo.nature.tropical", "Tropical Foliage", "Long tropical leaves that fan cleanly along a stroke.", "nature", BrushTip.Leaf, 64f, .9f, .48f, .64f, .7f,
            BrushDynamics(scatter = .34f, rotation = .28f, shapeRatio = .46f, hardness = .94f, jitter = .16f), listOf(refs.leafTropicalA, refs.leafTropicalB), refs.grainOrganic,
            StampAngleMode.DirectionJitter, angleJitter = .28f, scaleY = .48f, scatterAlong = .12f, scatterAcross = .34f, stampCount = 2, stampCountJitter = .24f, grainScale = .65f,
            pressureScatter = .35f, pressureStampCount = .45f, startTaper = .14f, endTaper = .2f),
        authoredBrush("neo.nature.leaf-canopy", "Leaf Canopy", "Dense mixed leaves for quickly building full tree crowns.", "nature", BrushTip.Leaf, 76f, .76f, .24f, .55f, .72f,
            BrushDynamics(grain = .12f, scatter = .58f, rotation = .62f, shapeRatio = .72f, hardness = .8f, jitter = .38f), listOf(refs.leafBroadA, refs.leafBroadB, refs.leafBroadC), refs.grainOrganic,
            StampAngleMode.Randomized, angleJitter = .88f, scaleY = .78f, scatterAlong = .3f, scatterAcross = .62f, stampCount = 5, stampCountJitter = .5f, grainScale = 1.1f,
            pressureScatter = .58f, pressureStampCount = .7f),
        authoredBrush("neo.nature.grass-wild", "Wild Grass", "Irregular tall blades with lively pressure-controlled density.", "nature", BrushTip.Grass, 58f, .86f, .3f, .7f, .68f,
            BrushDynamics(scatter = .4f, rotation = .18f, shapeRatio = .34f, hardness = .95f, jitter = .22f), listOf(refs.grassWildA, refs.grassWildB), refs.grainOrganic,
            StampAngleMode.DirectionJitter, angleJitter = .22f, scaleY = .44f, scatterAlong = .12f, scatterAcross = .42f, stampCount = 3, stampCountJitter = .32f, grainScale = .62f,
            pressureScatter = .42f, pressureStampCount = .62f, startTaper = .12f, endTaper = .28f),
        authoredBrush("neo.nature.grass-meadow", "Meadow Grass", "Fine grouped blades for soft fields and grassy edges.", "nature", BrushTip.Grass, 38f, .78f, .27f, .68f, .72f,
            BrushDynamics(scatter = .5f, rotation = .14f, shapeRatio = .3f, hardness = .9f, jitter = .3f), listOf(refs.grassMeadowA, refs.grassMeadowB), refs.grainOrganic,
            StampAngleMode.DirectionJitter, angleJitter = .18f, scaleY = .36f, scatterAlong = .18f, scatterAcross = .52f, stampCount = 4, stampCountJitter = .4f, grainScale = .5f,
            pressureScatter = .48f, pressureStampCount = .68f, startTaper = .14f, endTaper = .3f),
        authoredBrush("neo.nature.fern", "Fern Frond", "Readable lateral leaflets arranged around a flexible central stem.", "nature", BrushTip.Grass, 54f, .9f, .68f, .62f, .7f,
            BrushDynamics(scatter = .16f, rotation = .12f, shapeRatio = .42f, hardness = .92f, jitter = .12f), listOf(refs.fernA, refs.fernB), refs.grainOrganic,
            StampAngleMode.DirectionJitter, angleJitter = .12f, scaleY = .5f, scatterAlong = .06f, scatterAcross = .14f, stampCount = 1, stampCountJitter = .16f, grainScale = .7f,
            pressureScatter = .2f, startTaper = .2f, endTaper = .32f),
        authoredBrush("neo.nature.pine-needles", "Pine Needles", "Crisp needle sprays for conifer texture and sharp accents.", "nature", BrushTip.Grass, 34f, .88f, .36f, .66f, .72f,
            BrushDynamics(scatter = .25f, rotation = .12f, shapeRatio = .28f, hardness = .98f, jitter = .14f), listOf(refs.pineNeedleA, refs.pineNeedleB), refs.grainOrganic,
            StampAngleMode.DirectionJitter, angleJitter = .16f, scaleY = .38f, scatterAlong = .08f, scatterAcross = .26f, stampCount = 2, stampCountJitter = .24f, grainScale = .5f,
            pressureScatter = .28f, pressureStampCount = .36f, endTaper = .24f),
        authoredBrush("neo.nature.pine-bough", "Pine Bough", "Full branching needle silhouettes that follow the painted gesture.", "nature", BrushTip.Grass, 72f, .86f, .58f, .62f, .68f,
            BrushDynamics(scatter = .2f, rotation = .1f, shapeRatio = .42f, hardness = .94f, jitter = .12f), listOf(refs.pineBoughA, refs.pineBoughB), refs.grainOrganic,
            StampAngleMode.DirectionJitter, angleJitter = .12f, scaleY = .48f, scatterAlong = .08f, scatterAcross = .2f, stampCount = 1, stampCountJitter = .18f, grainScale = .85f,
            pressureScatter = .25f, startTaper = .12f, endTaper = .22f),
        authoredBrush("neo.nature.hedge", "Hedge", "Broken clustered foliage for shaped shrubs and distant tree lines.", "nature", BrushTip.Leaf, 68f, .72f, .22f, .52f, .76f,
            BrushDynamics(grain = .22f, scatter = .34f, rotation = .7f, shapeRatio = .78f, hardness = .78f, jitter = .36f), listOf(refs.hedgeA, refs.hedgeB), refs.grainOrganic,
            StampAngleMode.Randomized, angleJitter = .9f, scaleY = .76f, scatterAlong = .24f, scatterAcross = .4f, stampCount = 4, stampCountJitter = .46f, grainScale = 1.2f,
            pressureScatter = .5f, pressureStampCount = .64f),
        authoredBrush("neo.nature.branch", "Branch", "Tapered woody forks aligned to the direction of each stroke.", "nature", BrushTip.Bark, 46f, .94f, .72f, .78f, .66f,
            BrushDynamics(grain = .28f, scatter = .08f, rotation = .08f, shapeRatio = .24f, hardness = .96f, jitter = .08f), listOf(refs.branchA, refs.branchB), refs.grainBark,
            StampAngleMode.DirectionJitter, angleJitter = .08f, scaleY = .26f, scatterAlong = .04f, scatterAcross = .08f, stampCount = 1, stampCountJitter = .12f, grainScale = .65f,
            pressureScatter = .12f, startTaper = .28f, endTaper = .42f),
        authoredBrush("neo.nature.twig", "Twig", "Fine forked twigs for natural joins, stems and winter detail.", "nature", BrushTip.Bark, 24f, .92f, .78f, .84f, .68f,
            BrushDynamics(grain = .18f, scatter = .1f, rotation = .08f, shapeRatio = .18f, hardness = .98f, jitter = .06f), listOf(refs.twigA, refs.twigB), refs.grainBark,
            StampAngleMode.DirectionJitter, angleJitter = .1f, scaleY = .2f, scatterAlong = .04f, scatterAcross = .1f, stampCount = 1, stampCountJitter = .1f, grainScale = .5f,
            pressureScatter = .14f, startTaper = .34f, endTaper = .52f),
        authoredBrush("neo.nature.bark", "Bark", "Directional bark fragments with a fibrous canvas-anchored grain.", "nature", BrushTip.Bark, 58f, .7f, .25f, .58f, .78f,
            BrushDynamics(grain = .68f, scatter = .18f, rotation = .1f, shapeRatio = .34f, hardness = .72f, jitter = .2f), listOf(refs.barkFragmentA, refs.barkFragmentB), refs.grainBark,
            StampAngleMode.DirectionJitter, angleJitter = .14f, scaleY = .38f, scatterAlong = .1f, scatterAcross = .2f, stampCount = 2, stampCountJitter = .28f, grainScale = 1.35f,
            grainMovement = GrainMovement.Canvas, pressureScatter = .25f, pressureStampCount = .32f),
        authoredBrush("neo.nature.moss", "Moss", "Soft irregular clumps for stones, trunks and damp surfaces.", "nature", BrushTip.Spray, 48f, .6f, .2f, .5f, .82f,
            BrushDynamics(grain = .42f, scatter = .7f, rotation = .86f, shapeRatio = .88f, hardness = .58f, jitter = .46f), listOf(refs.mossA, refs.mossB), refs.grainOrganic,
            StampAngleMode.Randomized, angleJitter = 1f, scaleY = .86f, scatterAlong = .42f, scatterAcross = .74f, stampCount = 5, stampCountJitter = .56f, grainScale = 1.5f,
            pressureScatter = .7f, pressureStampCount = .78f),
        authoredBrush("neo.nature.ground-cover", "Ground Cover", "Low organic clusters for forest floors and distant undergrowth.", "nature", BrushTip.Spray, 62f, .58f, .18f, .48f, .84f,
            BrushDynamics(grain = .5f, scatter = .78f, rotation = .94f, shapeRatio = .64f, hardness = .62f, jitter = .52f), listOf(refs.mossA, refs.mossB, refs.hedgeA, refs.hedgeB), refs.grainOrganic,
            StampAngleMode.Randomized, angleJitter = 1f, scaleY = .58f, scatterAlong = .5f, scatterAcross = .82f, stampCount = 6, stampCountJitter = .62f, grainScale = 1.8f,
            pressureScatter = .76f, pressureStampCount = .82f),
    )
}
