package com.neoworksuite.neocanvas.brushes

internal object PaintingBrushes {
    val brushes = listOf(
        authoredBrush("neo.painting.round", "Round Paint", "Responsive opaque round for general painting.", "painting", BrushTip.Round, 28f, .82f, .1f, .9f, .8f, BrushDynamics(hardness = .76f), listOf(BuiltInBrushAssetRefs.roundSoft), scaleX = .9f, scaleY = .9f),
        authoredBrush("neo.painting.flat", "Flat Paint", "A direction-led flat brush for planes and edges.", "painting", BrushTip.Flat, 36f, .78f, .14f, .8f, .7f, BrushDynamics(shapeRatio = .5f, hardness = .8f), listOf(BuiltInBrushAssetRefs.bristleFlat), BuiltInBrushAssetRefs.grainCanvas, angleMode = StampAngleMode.Direction, scaleX = 1.25f, scaleY = .52f),
        authoredBrush("neo.painting.filbert", "Filbert", "Rounded flat bristles for soft-edged painterly strokes.", "painting", BrushTip.Bristle, 34f, .72f, .12f, .9f, .8f, BrushDynamics(grain = .25f, shapeRatio = .58f, hardness = .62f), listOf(BuiltInBrushAssetRefs.roundSoft), BuiltInBrushAssetRefs.grainCanvas, angleMode = StampAngleMode.DirectionJitter, angleJitter = .06f, scaleX = 1.25f, scaleY = .58f),
        authoredBrush("neo.dry-paint", "Dry Paint", "Broken bristle paint that catches the canvas texture.", "painting", BrushTip.DryPaint, 32f, .62f, .16f, .8f, 1f, BrushDynamics(grain = .7f, hardness = .6f), listOf(BuiltInBrushAssetRefs.bristleFlat), BuiltInBrushAssetRefs.grainDryPaint, angleMode = StampAngleMode.DirectionJitter, angleJitter = .1f, scaleX = 1.35f, scaleY = .5f),
        authoredBrush("neo.painting.gouache", "Opaque Gouache", "Dense matte paint with a subtly chalky edge.", "painting", BrushTip.Bristle, 30f, .88f, .13f, .75f, .7f, BrushDynamics(grain = .3f, hardness = .74f, wetMix = .2f), listOf(BuiltInBrushAssetRefs.bristleFlat), BuiltInBrushAssetRefs.grainChalk, angleMode = StampAngleMode.DirectionJitter, angleJitter = .05f, scaleY = .7f),
        authoredBrush("neo.painting.oil-bristle", "Oil Bristle", "Loaded oil bristles with visible strand separation.", "painting", BrushTip.Bristle, 40f, .76f, .11f, .9f, .75f, BrushDynamics(grain = .38f, hardness = .68f, wetMix = .62f), listOf(BuiltInBrushAssetRefs.bristleFlat), BuiltInBrushAssetRefs.grainCanvas, angleMode = StampAngleMode.DirectionJitter, angleJitter = .08f, scaleX = 1.35f, scaleY = .56f),
        authoredBrush("neo.painting.watercolour", "Watercolour Wash", "Transparent granulating wash with pooled soft edges.", "painting", BrushTip.Water, 52f, .2f, .09f, .3f, 1f, BrushDynamics(grain = .2f, hardness = .12f, wetMix = .95f), listOf(BuiltInBrushAssetRefs.roundSoft), BuiltInBrushAssetRefs.grainPaper, scaleX = 1.25f, scaleY = .95f, grainMovement = GrainMovement.Canvas),
        authoredBrush("neo.painting.glaze", "Soft Glaze", "Low-opacity colour glaze for gradual modelling.", "painting", BrushTip.SoftRound, 60f, .11f, .08f, .15f, 1f, BrushDynamics(hardness = .04f, wetMix = .35f), listOf(BuiltInBrushAssetRefs.roundSoft), BuiltInBrushAssetRefs.grainPaper, scaleX = 1.4f, scaleY = 1.05f, grainScale = 1.8f, grainMovement = GrainMovement.Canvas),
    )
}
