package com.neoworksuite.neocanvas.brushes

internal object TextureBrushes {
    val brushes = listOf(
        authoredBrush("neo.textures.graphite", "Graphite Grain", "Broad graphite grain for shading and rubbings.", "textures", BrushTip.Chalk, 42f, .38f, .2f, .5f, .9f, BrushDynamics(grain = .85f, hardness = .38f), listOf(BuiltInBrushAssetRefs.charcoal), BuiltInBrushAssetRefs.grainGraphite, angleMode = StampAngleMode.Randomized, angleJitter = 1f, scatterAcross = .08f, stampCount = 2),
        authoredBrush("neo.textures.spray", "Spray Dust", "Fine dispersed aerosol texture with a soft footprint.", "textures", BrushTip.Spray, 46f, .34f, .22f, .4f, .9f, BrushDynamics(scatter = .5f, hardness = .25f), listOf(BuiltInBrushAssetRefs.roundSoft), BuiltInBrushAssetRefs.grainChalk, angleMode = StampAngleMode.Randomized, angleJitter = 1f, scatterAlong = .18f, scatterAcross = .36f, stampCount = 3, stampCountJitter = .35f, pressureScatter = .7f),
        authoredBrush("neo.textures.stipple", "Stipple", "Pressure-built clustered dots for controlled value.", "textures", BrushTip.Spray, 28f, .58f, .28f, .4f, .8f, BrushDynamics(scatter = .35f, hardness = .9f), listOf(BuiltInBrushAssetRefs.mossA, BuiltInBrushAssetRefs.mossB), angleMode = StampAngleMode.Randomized, angleJitter = 1f, scaleX = .45f, scaleY = .45f, scatterAlong = .12f, scatterAcross = .28f, stampCount = 2),
        authoredBrush("neo.textures.paper", "Paper Grain", "Stationary paper tooth for glazing texture into colour.", "textures", BrushTip.DryPaint, 50f, .24f, .34f, .25f, 1f, BrushDynamics(grain = .82f, shapeRatio = .56f, hardness = .3f), grain = BuiltInBrushAssetRefs.grainPaper, grainScale = .8f, grainMovement = GrainMovement.Canvas),
        authoredBrush("neo.textures.rock", "Rock Grain", "Angular stony breakup for terrain and masonry.", "textures", BrushTip.Bark, 48f, .48f, .24f, .55f, .8f, BrushDynamics(grain = .7f, hardness = .62f), listOf(BuiltInBrushAssetRefs.barkFragmentA, BuiltInBrushAssetRefs.barkFragmentB), BuiltInBrushAssetRefs.grainStone, angleMode = StampAngleMode.Randomized, angleJitter = 1f, scatterAlong = .08f, scatterAcross = .12f),
        authoredBrush("neo.textures.distressed", "Distressed Paint", "Worn broken paint for weathered edges and overlays.", "textures", BrushTip.DryPaint, 54f, .46f, .22f, .5f, .9f, BrushDynamics(grain = .88f, hardness = .5f, jitter = .18f), listOf(BuiltInBrushAssetRefs.charcoal, BuiltInBrushAssetRefs.bristleFlat), BuiltInBrushAssetRefs.grainDryPaint, angleMode = StampAngleMode.DirectionJitter, angleJitter = .35f, scatterAlong = .1f, scatterAcross = .16f),
    )
}
