#!/usr/bin/env python3
"""Validate original brush sources and generate deterministic KMP asset catalogues."""
from __future__ import annotations
import argparse, hashlib, json, struct, sys, zlib
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
MANIFEST=ROOT/"assets/brushes/manifest.json"
REFS=ROOT/"brushes/src/commonMain/kotlin/com/neoworksuite/neocanvas/brushes/BuiltInBrushAssetRefs.kt"
DATA=ROOT/"renderer/src/commonMain/kotlin/com/neoworksuite/neocanvas/renderer/BuiltInBrushAssetData.kt"

def read_png(path: Path) -> tuple[int,int,bytes]:
    data=path.read_bytes(); assert data[:8]==b"\x89PNG\r\n\x1a\n", f"{path}: invalid PNG"
    pos=8; width=height=None; payload=bytearray()
    while pos<len(data):
        length=struct.unpack(">I",data[pos:pos+4])[0]; kind=data[pos+4:pos+8]; chunk=data[pos+8:pos+8+length]; pos+=12+length
        if kind==b"IHDR":
            width,height,depth,color,compression,filter_method,interlace=struct.unpack(">IIBBBBB",chunk)
            assert depth==8 and color==0 and compression==0 and filter_method==0 and interlace==0, f"{path}: unsupported PNG"
        elif kind==b"IDAT": payload.extend(chunk)
        elif kind==b"IEND": break
    assert width and height
    raw=zlib.decompress(payload); stride=width+1; assert len(raw)==stride*height
    pixels=bytearray()
    for y in range(height):
        row=raw[y*stride:(y+1)*stride]; assert row[0]==0, f"{path}: only filter 0 is accepted"; pixels.extend(row[1:])
    return width,height,bytes(pixels)

def encode(width:int,height:int,pixels:bytes)->bytes:
    out=bytearray(b"NEOMASK1"+struct.pack(">HH",width,height)); i=0
    while i<len(pixels):
        value=pixels[i]; count=1
        while i+count<len(pixels) and pixels[i+count]==value and count<65535: count+=1
        out+=struct.pack(">HB",count,value); i+=count
    return bytes(out)

def runs(pixels:bytes)->list[int]:
    result=[]; i=0
    while i<len(pixels):
        value=pixels[i]; count=1
        while i+count<len(pixels) and pixels[i+count]==value and count<65535: count+=1
        result.extend((count,value)); i+=count
    return result

def prop(asset_id:str)->str:
    parts=asset_id.split('-'); return parts[0]+''.join(part[:1].upper()+part[1:] for part in parts[1:])

def render_refs(items:list[dict])->str:
    lines=["package com.neoworksuite.neocanvas.brushes","","/** Generated by scripts/prepare-brush-assets.py. */","object BuiltInBrushAssetRefs {"]
    for item in items: lines.append(f'    val {prop(item["id"])} = BrushAssetRef("{item["id"]}", "{item["sha256"]}")')
    shapes=', '.join(prop(i['id']) for i in items if i['kind']=='shape'); grains=', '.join(prop(i['id']) for i in items if i['kind']=='grain')
    lines += ["",f"    val shapes: List<BrushAssetRef> = listOf({shapes})",f"    val grains: List<BrushAssetRef> = listOf({grains})","    val all: List<BrushAssetRef> = shapes + grains","}",""]
    return '\n'.join(lines)

def render_data(items:list[dict], decoded:dict[str,tuple[int,int,bytes]])->str:
    lines=["package com.neoworksuite.neocanvas.renderer","","import com.neoworksuite.neocanvas.brushes.BuiltInBrushAssetRefs","","/** Generated by scripts/prepare-brush-assets.py. */","internal object BuiltInBrushAssetData {","    val records: List<BuiltInBrushAssetRecord>","        get() = listOf("]
    for index,_ in enumerate(items): lines.append(f"            record{index}(),")
    lines += ["        )",""]
    for index,item in enumerate(items):
        width,height,pixels=decoded[item['id']]; values=runs(pixels)
        lines += [f"    private fun record{index}(): BuiltInBrushAssetRecord = BuiltInBrushAssetRecord(",f"        ref = BuiltInBrushAssetRefs.{prop(item['id'])},",f"        width = {width},",f"        height = {height},","        runs = intArrayOf("]
        for i in range(0,len(values),24): lines.append("            "+", ".join(map(str,values[i:i+24]))+",")
        lines += ["        ),","    )",""]
    lines += ["}",""]
    return '\n'.join(lines)

def main()->int:
    parser=argparse.ArgumentParser(); parser.add_argument('--verify',action='store_true'); args=parser.parse_args()
    doc=json.loads(MANIFEST.read_text()); assert doc.get('format')==1; items=doc.get('assets'); assert isinstance(items,list) and items
    ids=[i['id'] for i in items]; assert ids==sorted(ids) and len(ids)==len(set(ids)); assert len({i['sha256'] for i in items})==len(items)
    decoded={}
    for item in items:
        path=MANIFEST.parent/item['source']; width,height,pixels=read_png(path)
        assert (width,height)==(item['width'],item['height']); assert 1<=width<=512 and 1<=height<=512; assert any(pixels)
        if item['kind']=='shape':
            edge=pixels[:width]+pixels[-width:]+bytes(pixels[y*width] for y in range(height))+bytes(pixels[y*width+width-1] for y in range(height))
            assert not any(edge), f"{item['id']}: shape touches rectangular border"
        encoded=encode(width,height,pixels); assert hashlib.sha256(encoded).hexdigest()==item['sha256'], f"{item['id']}: hash mismatch"
        decoded[item['id']]=(width,height,pixels)
    outputs={REFS:render_refs(items),DATA:render_data(items,decoded)}
    if args.verify:
        stale=[str(path.relative_to(ROOT)) for path,text in outputs.items() if not path.is_file() or path.read_text()!=text]
        if stale:
            print("Stale generated brush assets: "+", ".join(stale),file=sys.stderr); return 1
    else:
        for path,text in outputs.items(): path.parent.mkdir(parents=True,exist_ok=True); path.write_text(text)
    print(f"Brush assets OK: {len(items)} ({sum(i['kind']=='shape' for i in items)} shapes, {sum(i['kind']=='grain' for i in items)} grains)")
    return 0
if __name__=='__main__': raise SystemExit(main())
